# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171109_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompBTstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CompMTstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CompPhdstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContBTstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContMTstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContPhdstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cbt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ContBTstudents')),
                ('cmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ContMTstudents')),
                ('cobt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CompBTstudents')),
                ('comt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CompMTstudents')),
                ('cophd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CompPhdstudents')),
                ('cphd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ContPhdstudents')),
            ],
        ),
    ]
