# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_compbtstudents_compmtstudents_compphdstudents_contbtstudents_contmtstudents_contphdstudents_publicat'),
    ]

    operations = [
        migrations.CreateModel(
            name='recognitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recg', models.CharField(max_length=500)),
            ],
        ),
    ]
