# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171111_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='agency',
            new_name='agency1',
        ),
    ]
