# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171111_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
