# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pi', models.CharField(max_length=10)),
                ('agency', models.CharField(max_length=10)),
                ('startyear', models.CharField(max_length=10)),
                ('endyear', models.CharField(max_length=10)),
            ],
        ),
    ]
